# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  workspace 'project'
  # Pods for project
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn'
  pod 'GoogleUtilities'

end
